# Generated by Django 5.1 on 2024-09-30 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_pets_amigos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("hora", models.TimeField()),
                ("motivo", models.TextField(blank=True, null=True)),
                (
                    "servico",
                    models.CharField(
                        choices=[
                            ("banho", "Banho"),
                            ("banho_e_tosa", "Banho e Tosa"),
                            ("exames", "Exames"),
                            ("vacinas", "Vacinas"),
                            ("outros_servicos", "Outros Serviços"),
                        ],
                        max_length=50,
                    ),
                ),
                ("cancelado", models.BooleanField(default=False)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("telefone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="fotos_pets/"),
                ),
                ("peso", models.DecimalField(decimal_places=2, max_digits=5)),
                ("idade", models.IntegerField()),
                ("raca", models.CharField(max_length=100)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("macho", "Macho"), ("femea", "Fêmea")], max_length=10
                    ),
                ),
                (
                    "tamanho",
                    models.CharField(
                        choices=[
                            ("pequeno", "Pequeno"),
                            ("medio", "Médio"),
                            ("grande", "Grande"),
                        ],
                        max_length=10,
                    ),
                ),
                ("vacinas", models.TextField(blank=True, null=True)),
                ("remedios", models.TextField(blank=True, null=True)),
                ("alergias", models.TextField(blank=True, null=True)),
                ("outros", models.TextField(blank=True, null=True)),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
