# Generated by Django 5.1.2 on 2024-10-15 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("endereco", models.CharField(max_length=255)),
                ("numero", models.IntegerField()),
                ("complemento", models.CharField(max_length=100)),
                ("bairro", models.CharField(max_length=100)),
                ("localidade", models.CharField(max_length=100)),
                ("uf", models.CharField(max_length=2)),
                ("telefone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("hora", models.TimeField()),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("finalizado", models.BooleanField(default=False)),
                ("pago", models.BooleanField(default=False)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.cliente"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("cpf_cnpj", models.CharField(max_length=20)),
                ("telefone", models.CharField(max_length=15)),
                ("crmv", models.CharField(max_length=20)),
                ("endereco", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metodo_pagamento", models.CharField(max_length=20)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "agendamento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.agendamento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("especie", models.CharField(max_length=50)),
                ("raca", models.CharField(max_length=50)),
                ("idade", models.IntegerField()),
                ("peso", models.FloatField()),
                ("vacina", models.CharField(blank=True, max_length=100)),
                ("remedios", models.CharField(blank=True, max_length=100)),
                ("outros", models.TextField(blank=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.cliente"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agendamento",
            name="pet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.pet"
            ),
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duracao", models.DurationField()),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.empresa"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agendamento",
            name="servico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.servico"
            ),
        ),
    ]
